# Topic 3. PyTorch Tensors

## Introduction to PyTorch

## 1. Import libraries

In [66]:
import torch
import numpy as np

## 2. torch.empty()

In [67]:
x = torch.empty(3, 4)
print(type(x))
print(x)

<class 'torch.Tensor'>
tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])


## 3. Zeros, ones and random numbers

In [68]:
zeros = torch.zeros(2, 3)
print(zeros)

ones = torch.ones(2, 3)
print(ones)

torch.manual_seed(1729)
random = torch.rand(2, 3)
print(random)

tensor([[0., 0., 0.],
        [0., 0., 0.]])
tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[0.3126, 0.3791, 0.3087],
        [0.0736, 0.4216, 0.0691]])


## 4. seeding

In [69]:
torch.manual_seed(1729)
random1 = torch.rand(2, 3)
print(random1)

random2 = torch.rand(2, 3)
print(random2)

torch.manual_seed(1729)
random3 = torch.rand(2, 3)
print(random3)

random4 = torch.rand(2, 3)
print(random4)

tensor([[0.3126, 0.3791, 0.3087],
        [0.0736, 0.4216, 0.0691]])
tensor([[0.2332, 0.4047, 0.2162],
        [0.9927, 0.4128, 0.5938]])
tensor([[0.3126, 0.3791, 0.3087],
        [0.0736, 0.4216, 0.0691]])
tensor([[0.2332, 0.4047, 0.2162],
        [0.9927, 0.4128, 0.5938]])


## 5. tensor — shape

In [70]:
x = torch.empty(2, 2, 3)
print(x.shape)
print(x)

torch.Size([2, 2, 3])
tensor([[[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]]])


## 6. *_like()

In [71]:
x = torch.empty(2, 2, 3)
print(x.shape)
print(x)

empty_like_x = torch.empty_like(x)
print(empty_like_x.shape)
print(empty_like_x)

zeros_like_x = torch.zeros_like(x)
print(zeros_like_x.shape)
print(zeros_like_x)

ones_like_x = torch.ones_like(x)
print(ones_like_x.shape)
print(ones_like_x)

rand_like_x = torch.rand_like(x)
print(rand_like_x.shape)
print(rand_like_x)

torch.Size([2, 2, 3])
tensor([[[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]]])
torch.Size([2, 2, 3])
tensor([[[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]]])
torch.Size([2, 2, 3])
tensor([[[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]]])
torch.Size([2, 2, 3])
tensor([[[1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.]]])
torch.Size([2, 2, 3])
tensor([[[0.6128, 0.1519, 0.0453],
         [0.5035, 0.9978, 0.3884]],

        [[0.6929, 0.1703, 0.1384],
         [0.4759, 0.7481, 0.0361]]])


## 7. Creating a tensor with data

In [72]:
some_constants = torch.tensor([[3.1415926, 2.71828], [1.61803, 0.0072897]])
print(some_constants)

some_integers = torch.tensor((2, 3, 5, 7, 11, 13, 17, 19))
print(some_integers)

more_integers = torch.tensor(((2, 4, 6), [3, 6, 9]))
print(more_integers)

tensor([[3.1416, 2.7183],
        [1.6180, 0.0073]])
tensor([ 2,  3,  5,  7, 11, 13, 17, 19])
tensor([[2, 4, 6],
        [3, 6, 9]])


## 8. dtype

In [73]:
a = torch.ones((2, 3), dtype=torch.int16)
print(a)

b = torch.rand((2, 3), dtype=torch.float64) * 20.
print(b)

c = b.to(torch.int32)
print(c)

tensor([[1, 1, 1],
        [1, 1, 1]], dtype=torch.int16)
tensor([[ 0.9956,  1.4148,  5.8364],
        [11.2406, 11.2083, 11.6692]], dtype=torch.float64)
tensor([[ 0,  1,  5],
        [11, 11, 11]], dtype=torch.int32)


## 9. tensor's characteristics

In [74]:
tensor = torch.rand(3,4)

print(f"Tensor: {tensor}")
print(f"Shape of tensor: {tensor.shape}")
print(f"Datatype of tensor: {tensor.dtype}")
print(f"Device tensor is stored on: {tensor.device}")

Tensor: tensor([[0.6146, 0.5999, 0.5013, 0.9397],
        [0.8656, 0.5207, 0.6865, 0.3614],
        [0.6493, 0.2633, 0.4762, 0.0548]])
Shape of tensor: torch.Size([3, 4])
Datatype of tensor: torch.float32
Device tensor is stored on: cpu


## 10. tensor + scalar

In [75]:
ones = torch.zeros(2, 2) + 1
twos = torch.ones(2, 2) * 2
threes = (torch.ones(2, 2) * 7 - 1) / 2
fours = twos ** 2
sqrt2s = twos ** 0.5

print(ones)
print(twos)
print(threes)
print(fours)
print(sqrt2s)

tensor([[1., 1.],
        [1., 1.]])
tensor([[2., 2.],
        [2., 2.]])
tensor([[3., 3.],
        [3., 3.]])
tensor([[4., 4.],
        [4., 4.]])
tensor([[1.4142, 1.4142],
        [1.4142, 1.4142]])


## 11. Tensor + tensor

In [76]:
powers2 = twos ** torch.tensor([[1, 2], [3, 4]])
print(powers2)

fives = ones + fours
print(fives)

dozens = threes * fours
print(dozens)

threes = threes
print(threes)

tensor([[ 2.,  4.],
        [ 8., 16.]])
tensor([[5., 5.],
        [5., 5.]])
tensor([[12., 12.],
        [12., 12.]])
tensor([[3., 3.],
        [3., 3.]])


## 12. RuntimeError (size of tensor)

In [77]:
a = torch.rand(2, 3)
b = torch.rand(3, 2)

print(a + b)

RuntimeError: The size of tensor a (3) must match the size of tensor b (2) at non-singleton dimension 1

## 13. Indexing and slicing

In [ ]:
tensor = torch.ones(4, 4)
print(f"First row: {tensor[0]}")
print(f"First column: {tensor[:, 0]}")
print(f"Last column: {tensor[..., -1]}")
tensor[:,1] = 0
print(tensor)

First row: tensor([1., 1., 1., 1.])
First column: tensor([1., 1., 1., 1.])
Last column: tensor([1., 1., 1., 1.])
tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])


## 14. Concatenating tensors 

In [88]:
# torch.cat
x = torch.tensor([[1, 2], [3, 4]])
y = torch.tensor([[5, 6]])

# Конкатенація вздовж 0-го виміру
result = torch.cat((x, y), dim=0)
print(result)

tensor([[1, 2],
        [3, 4],
        [5, 6]])


In [91]:
# torch.cat
x = torch.tensor([[1, 2], [3, 4]])
y = torch.tensor([[5, 6], [7, 8]])

# Конкатенація вздовж 0-го виміру
result = torch.cat((x, y), dim=0)
print(result)

tensor([[1, 2],
        [3, 4],
        [5, 6],
        [7, 8]])


In [ ]:
# torch.cat
x = torch.tensor([[1, 2], [3, 4]])
y = torch.tensor([[5, 6], [7, 8]])

# Конкатенація вздовж 1-го виміру
result = torch.cat((x, y), dim=1)
print(result)

tensor([[1, 2, 5, 6],
        [3, 4, 7, 8]])


## 15. Stack tensors 

In [94]:
#torch.stack
x = torch.tensor([[1, 2], [3, 4]])
y = torch.tensor([[5, 6], [7, 8]])

# Стек вздовж нового виміру (вимір 0)
result = torch.stack((x, y), dim=0)
print(result)

tensor([[[1, 2],
         [3, 4]],

        [[5, 6],
         [7, 8]]])


In [95]:
#torch.stack
x = torch.tensor([[1, 2], [3, 4]])
y = torch.tensor([[5, 6], [7, 8]])

# Стек вздовж нового виміру (вимір 1)
result = torch.stack((x, y), dim=1)
print(result)

tensor([[[1, 2],
         [5, 6]],

        [[3, 4],
         [7, 8]]])


## 16. RuntimeError (each tensor to be equal size)

In [ ]:
#torch.stack
x = torch.tensor([[1, 2], [3, 4]])
y = torch.tensor([[5, 6]])

# Стек вздовж нового виміру (вимір 0)
result = torch.stack((x, y), dim=0)
print(result)


RuntimeError: stack expects each tensor to be equal size, but got [2, 2] at entry 0 and [1, 2] at entry 1

## 17. Tensor broadcasting

In [78]:
rand = torch.rand(2, 4)
doubled = rand * (torch.ones(1, 4) * 2)

print(rand)
print(doubled)

tensor([[0.7220, 0.8217, 0.2612, 0.7375],
        [0.8328, 0.8444, 0.2941, 0.3788]])
tensor([[1.4439, 1.6434, 0.5224, 1.4750],
        [1.6657, 1.6888, 0.5882, 0.7576]])


## 18. Broadcasting

In [79]:
a = torch.ones(4, 3, 2)

b = a * torch.rand(3, 2)
print(b)

tensor([[[0.4567, 0.0649],
         [0.6677, 0.7826],
         [0.1332, 0.0023]],

        [[0.4567, 0.0649],
         [0.6677, 0.7826],
         [0.1332, 0.0023]],

        [[0.4567, 0.0649],
         [0.6677, 0.7826],
         [0.1332, 0.0023]],

        [[0.4567, 0.0649],
         [0.6677, 0.7826],
         [0.1332, 0.0023]]])


In [80]:
a = torch.ones(4, 3, 2)

c = a * torch.rand(3, 1)
print(c)

tensor([[[0.4945, 0.4945],
         [0.3857, 0.3857],
         [0.9883, 0.9883]],

        [[0.4945, 0.4945],
         [0.3857, 0.3857],
         [0.9883, 0.9883]],

        [[0.4945, 0.4945],
         [0.3857, 0.3857],
         [0.9883, 0.9883]],

        [[0.4945, 0.4945],
         [0.3857, 0.3857],
         [0.9883, 0.9883]]])


## 19. Failed broadcast №1

In [86]:
a = torch.ones(4, 3, 2)

b = a * torch.rand(4, 3)

RuntimeError: The size of tensor a (2) must match the size of tensor b (3) at non-singleton dimension 2

In [85]:
a = torch.ones(4, 3, 2)

d = a * torch.rand((0, ))

RuntimeError: The size of tensor a (2) must match the size of tensor b (0) at non-singleton dimension 2

In [84]:
a = torch.ones(4, 3, 2)

c = a * torch.rand(2, 3)

RuntimeError: The size of tensor a (2) must match the size of tensor b (3) at non-singleton dimension 2

## 20. Single-element tensors

In [99]:
agg = tensor.sum()
agg_item = agg.item()
print(tensor)
print(agg)
print(agg_item, type(agg_item))

tensor([[0.6146, 0.5999, 0.5013, 0.9397],
        [0.8656, 0.5207, 0.6865, 0.3614],
        [0.6493, 0.2633, 0.4762, 0.0548]])
tensor(6.5332)
6.533219337463379 <class 'float'>


## 21. In-place operations

In [100]:
print(f"{tensor} \n")
tensor.add_(5)
print(tensor)

tensor([[0.6146, 0.5999, 0.5013, 0.9397],
        [0.8656, 0.5207, 0.6865, 0.3614],
        [0.6493, 0.2633, 0.4762, 0.0548]]) 

tensor([[5.6146, 5.5999, 5.5013, 5.9397],
        [5.8656, 5.5207, 5.6865, 5.3614],
        [5.6493, 5.2633, 5.4762, 5.0548]])


## 22. PyTorch and NumPy

In [112]:
t = torch.ones(5)
print(f"t: {t}")

n = t.numpy()
print(f"n: {n}")

t: tensor([1., 1., 1., 1., 1.])
n: [1. 1. 1. 1. 1.]


In [113]:
t.add_(1)

print(f"t: {t}")
print(f"n: {n}")

t: tensor([2., 2., 2., 2., 2.])
n: [2. 2. 2. 2. 2.]


In [116]:
n = np.ones(5)
t = torch.from_numpy(n)
print(f"n: {n}")
print(f"t: {t}")

n: [1. 1. 1. 1. 1.]
t: tensor([1., 1., 1., 1., 1.], dtype=torch.float64)


In [115]:
np.add(n, 1, out=n)

print(f"t: {t}")
print(f"n: {n}")

t: tensor([2., 2., 2., 2., 2.], dtype=torch.float64)
n: [2. 2. 2. 2. 2.]


## 23. Transferring tensor to the graphics processor (GPU)

In [ ]:
# for Apple Silicon / MPS

if torch.backends.mps.is_available():
    tensor = tensor.to("mps")

print(tensor.device)

mps:0


In [118]:
# for checking MPS

test_tensor = torch.ones(3, 3)

print("Before:", test_tensor.device)

if torch.backends.mps.is_available():
    test_tensor = test_tensor.to("mps")

print("After:", test_tensor.device)

Before: cpu
After: mps:0


## 24. Working with tensor dimensions ( squeeze() and unsqueeze() )

In [119]:
a = torch.rand(3, 226, 226)
b = a.unsqueeze(0)

print(a.shape)
print(b.shape)

torch.Size([3, 226, 226])
torch.Size([1, 3, 226, 226])


In [120]:
a = torch.rand(1, 20)
print(a.shape)
print(a)

b = a.squeeze(0)
print(b.shape)
print(b)

c = torch.rand(2, 2)
print(c.shape)

d = c.squeeze(0)
print(d.shape)

torch.Size([1, 20])
tensor([[0.2368, 0.1394, 0.1721, 0.1751, 0.3851, 0.0732, 0.3118, 0.9180, 0.7293,
         0.5351, 0.5078, 0.8012, 0.5088, 0.3142, 0.8068, 0.6503, 0.4621, 0.6882,
         0.7282, 0.9156]])
torch.Size([20])
tensor([0.2368, 0.1394, 0.1721, 0.1751, 0.3851, 0.0732, 0.3118, 0.9180, 0.7293,
        0.5351, 0.5078, 0.8012, 0.5088, 0.3142, 0.8068, 0.6503, 0.4621, 0.6882,
        0.7282, 0.9156])
torch.Size([2, 2])
torch.Size([2, 2])


In [128]:
a = torch.ones(4, 3, 2)

c = a * torch.rand(3, 1)
print(c)

tensor([[[0.2961, 0.2961],
         [0.9811, 0.9811],
         [0.6110, 0.6110]],

        [[0.2961, 0.2961],
         [0.9811, 0.9811],
         [0.6110, 0.6110]],

        [[0.2961, 0.2961],
         [0.9811, 0.9811],
         [0.6110, 0.6110]],

        [[0.2961, 0.2961],
         [0.9811, 0.9811],
         [0.6110, 0.6110]]])


In [136]:
a = torch.ones(4, 3, 2)
b = torch.rand(3)
print(a)
print(b)

tensor([[[1., 1.],
         [1., 1.],
         [1., 1.]],

        [[1., 1.],
         [1., 1.],
         [1., 1.]],

        [[1., 1.],
         [1., 1.],
         [1., 1.]],

        [[1., 1.],
         [1., 1.],
         [1., 1.]]])
tensor([0.4142, 0.8224, 0.1484])


In [ ]:
a = torch.ones(4, 3, 2)
b = torch.rand(3)       # спроба помножити a * b призведе до помилки під час виконання
c = b.unsqueeze(1)      # змінити на двовимірний тензор, додавши в кінці новий dim (a.shape = [4,3,2], c.shape = [3,1])

print(c.shape)
print(a * c)            # трансляція знову працює!

torch.Size([3, 1])
tensor([[[0.9538, 0.9538],
         [0.9873, 0.9873],
         [0.8764, 0.8764]],

        [[0.9538, 0.9538],
         [0.9873, 0.9873],
         [0.8764, 0.8764]],

        [[0.9538, 0.9538],
         [0.9873, 0.9873],
         [0.8764, 0.8764]],

        [[0.9538, 0.9538],
         [0.9873, 0.9873],
         [0.8764, 0.8764]]])


## 25. Reshaping tensors

In [138]:
output3d = torch.rand(6, 20, 20)
print(output3d.shape)

input1d = output3d.reshape(6 * 20 * 20)
print(input1d.shape)

# також може викликати його як метод у модулі torch:
print(torch.reshape(output3d, (6 * 20 * 20,)).shape)

torch.Size([6, 20, 20])
torch.Size([2400])
torch.Size([2400])


In [139]:
# OPTIONAL — added for understanding reshape/view

x = torch.tensor([[1, 2], [3, 4]])

y = x.reshape(4)

print(x)
print(y)

y[0] = 100

print(x)
print(y)

tensor([[1, 2],
        [3, 4]])
tensor([1, 2, 3, 4])
tensor([[100,   2],
        [  3,   4]])
tensor([100,   2,   3,   4])


In [ ]:
# OPTIONAL — added for understanding clone()

x = torch.tensor([[1, 2], [3, 4]])

y = x.reshape(4).clone()

y[0] = 100

print(x)
print(y)

tensor([[1, 2],
        [3, 4]])
tensor([100,   2,   3,   4])
